// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACORGg3kMPvXIzR-7A5xIxAdWXT7q6Ddc',
    appId: '1:586103505088:android:abc3ea3fe124c4d3a3ed25',
    messagingSenderId: '586103505088',
    projectId: 'newproject-e9632',
    storageBucket: 'newproject-e9632.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfjKfjiUKR1uTgK7rcVfj8DNsraApZPE',
    appId: '1:586103505088:ios:1b15462e5d12697fa3ed25',
    messagingSenderId: '586103505088',
    projectId: 'newproject-e9632',
    storageBucket: 'newproject-e9632.appspot.com',
    iosBundleId: 'com.example.newproject',
  );
}
